AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: STS Broker

Parameters:

  Stage:
    Description: Stage name (Dev, Prod)
    AllowedValues:
      - Dev
      - Prod
    Type: String
    Default: Dev
    ConstraintDescription: Must specify Prod or Dev.

Resources:

  STSBrokerCore:
    Type: AWS::Serverless::Application
    Properties:
      Location: sts-broker-core/template.yaml
      Parameters:
        Stage: !Ref Stage

  NotifySlack:
    Type: AWS::Serverless::Application
    Properties:
      Location: slack/template.yaml
      Parameters:
        ApprovalNotificationTopicARN: !GetAtt STSBrokerCore.Outputs.ApprovalNotificationTopicARN

Outputs:
  STSBrokerAPI:
    Description: API Gateway endpoint URL for stage
    Value: !GetAtt STSBrokerCore.Outputs.STSBrokerAPI
  CognitoUserPoolID:
    Description: Cognito User Pool ID
    Value: !GetAtt STSBrokerCore.Outputs.CognitoUserPoolID
  CognitoUserPoolClientID:
    Description: Cognito User Pool client
    Value: !GetAtt STSBrokerCore.Outputs.CognitoUserPoolClientID