AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: STS Broker

Parameters:

  Stage:
    Description: Stage name (Dev, Prod)
    AllowedValues:
      - Dev
      - Prod
    Type: String
    Default: Prod
    ConstraintDescription: Must specify Prod or Dev.

  EvaluatePermissionRequestCodeUriBucket:
    Description: S3 Uri location for Lambda deployment package (S3 Bucket).
    Type: String
    Default: ''

  EvaluatePermissionRequestCodeUriKey:
    AllowedPattern: (^$|.*(zip))
    ConstraintDescription: This must be a .zip file.
    Description: S3 Uri location for Lambda deployment package (S3 Bucket key).
    Type: String
    Default: ''

Resources:

  STSBrokerCore:
    Type: AWS::Serverless::Application
    Properties:
      Location: sts-broker-core/packaged.yaml
      Parameters:
        Stage: !Ref Stage
        EvaluatePermissionRequestCodeUriBucket: !Ref EvaluatePermissionRequestCodeUriBucket
        EvaluatePermissionRequestCodeUriKey: !Ref EvaluatePermissionRequestCodeUriKey

  NotifySlack:
    Type: AWS::Serverless::Application
    Properties:
      Location: slack/packaged.yaml
      Parameters:
        ApprovalNotificationTopicARN: !GetAtt STSBrokerCore.Outputs.ApprovalNotificationTopicARN
        TeamPreferencesTableName: !GetAtt STSBrokerCore.Outputs.TeamPreferencesTableName

Outputs:
  STSBrokerAPI:
    Description: API Gateway endpoint URL for stage
    Value: !GetAtt STSBrokerCore.Outputs.STSBrokerAPI
  CognitoUserPoolID:
    Description: Cognito User Pool ID
    Value: !GetAtt STSBrokerCore.Outputs.CognitoUserPoolID
  CognitoUserPoolClientID:
    Description: Cognito User Pool client
    Value: !GetAtt STSBrokerCore.Outputs.CognitoUserPoolClientID
  ApproveRequestFunctionRoleARN:
    Description: ARN of the approval function. Must be included on the Assumed Role trust relationship.
    Value: !GetAtt STSBrokerCore.Outputs.ApproveRequestFunctionRoleARN