AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito User Pools Auth

Parameters:
  CognitoUserPoolName:
    Type: String
    Default: STSBrokerUserPool
  
  CognitoUserPoolClientName:
    Type: String
    Default: STSBrokerUserPoolClient

Resources:

  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref CognitoUserPoolName
      LambdaConfig:
        PreSignUp: !GetAtt PreSignupLambdaFunction.Arn
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      ClientName: !Ref CognitoUserPoolClientName
      GenerateSecret: false

  PreSignupLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async (event, context, callback) => {
          event.response = { autoConfirmUser: true }
          return event
        }
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs8.10
      Timeout: 3

  LambdaCognitoUserPoolExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PreSignupLambdaFunction.Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${MyCognitoUserPool}'
      # TODO: Add a CognitoUserPool Event Source to SAM to create this permission for you.
      # Events:
      #   CognitoUserPoolPreSignup:
      #     Type: CognitoUserPool
      #     Properties:
      #       UserPool: !Ref MyCognitoUserPool

Outputs:
    CognitoUserPoolARN:
      Value: !GetAtt MyCognitoUserPool.Arn
    CognitoUserPoolId:
      Description: "Cognito User Pool Id"
      Value: !Ref MyCognitoUserPool
    CognitoUserPoolClientId:
      Description: "Cognito User Pool Client Id"
      Value: !Ref MyCognitoUserPoolClient