AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito User Pools Auth

Parameters:
  CognitoUserPoolName:
    Type: String
    Default: STSBrokerUserPool
  
  CognitoUserPoolClientName:
    Type: String
    Default: STSBrokerUserPoolClient

Resources:

  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref CognitoUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
        - AttributeDataType: String
          Name: team
          Mutable: true
  
  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      ClientName: !Ref CognitoUserPoolClientName
      GenerateSecret: false

Outputs:
    CognitoUserPoolARN:
      Value: !GetAtt MyCognitoUserPool.Arn
    CognitoUserPoolID:
      Description: "Cognito User Pool ID"
      Value: !Ref MyCognitoUserPool
    CognitoUserPoolClientID:
      Description: "Cognito User Pool Client ID"
      Value: !Ref MyCognitoUserPoolClient